### ISSUE TITLE
pandas indexing issue

### ISSUE THREAD

**Issue by danielrosenbloom** [hddm-devs/kabuki#28]
When running approximate_map(), I get the following pandas warning, triggered in line 1076 of hierarchical.py (self.nodes_db['map'].ix[name] = value)

    SettingWithCopyWarning: 
    A value is trying to be set on a copy of a slice from a DataFrame
    
    See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

I am not sure if this warning has any downstream effects, but it appears that changing the line to the following resolves the issue:

    self.nodes_db.loc[name,'map'] = value

**Comment by twiecki** [comment]
Thanks!
